# Huggingface
embeddings_model: sentence-transformers/all-mpnet-base-v2
# Ollama
model: volo

mediawikis:
  - dnd5e
  - eberron
  - forgottenrealms
  - planescape
prompt: "What is a Tako?"
source: ./sources
