---
data_dir: ./data
# Huggingface
embeddings_model: sentence-transformers/all-mpnet-base-v2
introduction: Ah my good fellow!
# Sources
mediawikis:
  # - dnd4e
  - dnd5e
  - darksun
  - dragonlance
  - eberron
  # - exandria
  - forgottenrealms
  - greyhawk
  - planescape
  # - ravenloft
  - spelljammer
# Ollama
model: volo
question: How many eyestalks does a Beholder have?
settings:
  num_sources: 10
  repeat_penalty: 1.8
  temperature: 0
  top_k: 20
  top_p: 0.35
# Sources Path
source: ./sources
