---
name: Build Container
permissions: read-all
on:
  push:
    branches:
      - main

jobs:
  container-build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  container-scan:
    needs: [container-build]
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: aquasecurity/trivy-action@0.25.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:main
          format: sarif
          output: trivy-results-main.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results-main.sarif
