---
name: Integration Test
permissions: read-all
on:
  push:
# on:
#   pull_request_review:
#     types: [submitted]

jobs:
  embed-test:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    container:
      image: ollama/ollama
    steps:
      - uses: actions/checkout@v4
      - name: Install git
        run: apt-get install git sqlite3 -y
      - name: Setup Ollama
        run: |
          ollama serve &
          sleep 5
          ollama create volo -f ./Modelfile
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Requirements
        run: python -m pip install -r requirements.txt
      - name: Download Sources
        run: |
          python -m pip install huggingface-cli hf_transfer
          huggingface-cli login --token ${{ secrets.HF_TOKEN }}
          huggingface-cli download --repo-type space TotalSundae/dungeons-and-dragons --include *.xml --local-dir .
        env:
          HF_HUB_ENABLE_HF_TRANSFER: 1
      - name: Create Embeddings
        run: python main.py
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Chroma VectorDB Embeddings
          path: data/
