---
name: Integration Test
permissions: read-all
on:
  pull_request_review:
    types: [submitted]

jobs:
  container-build:
    if: >
      github.event.review.state == 'approved' ||
      contains(github.event.pull_request.assignees.*.login, 'tylertitsworth')
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  embed-test:
    needs: [container-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Sources
        run: |
          python -m pip install -U "huggingface-hub[cli]" hf_transfer
          huggingface-cli login --token ${{ secrets.HF_TOKEN }}
          huggingface-cli download --repo-type space TotalSundae/dungeons-and-dragons \
          --include *.xml \
          --local-dir . \
          --local-dir-use-symlinks False
          huggingface-cli download --repo-type space TotalSundae/dungeons-and-dragons \
          --include data/* \
          --local-dir . \
          --local-dir-use-symlinks False
        env:
          HF_HUB_ENABLE_HF_TRANSFER: 1
      - name: Create Embeddings
        run: |
          docker run --shm-size=7GB \
          -u root -w /home/user/app \
          -v $PWD/data:/home/user/app/test_data \
          -v $PWD/sources:/home/user/app/sources \
          ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:pr-${{ github.event.pull_request.number }} \
          bash -c "ollama serve & pip install pytest && pytest -W ignore::DeprecationWarning"
      - uses: actions/upload-artifact@v4
        with:
          name: Chroma VectorDB Embeddings
          path: data/
