---
name: Unit Tests
on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install requirements
      run: |
        python -m pip install pytest
        python -m pip install -r requirements.txt
    - name: Basic Unit Test
      run: pytest test/test.py -W ignore::DeprecationWarning
