---
name: Unit Tests
permissions: read-all
on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install requirements
      run: |
        python -m pip install pytest
        python -m pip install -r requirements.txt
    - name: Basic Unit Test
      run: pytest test/test.py -W ignore::DeprecationWarning
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          start: npx ts-node cypress/run.ts
          wait-on: 'http://localhost:8000'
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
