---
name: Unit Tests
permissions: read-all
on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install requirements
      run: |
        python -m pip install pytest
        python -m pip install -r requirements.txt
    - name: Basic Unit Test
      run: pytest test/test.py -W ignore::DeprecationWarning
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python Requirements
        run: python -m pip install -r requirements.txt
      - name: Setup Ollama
        run: |
          curl https://ollama.ai/install.sh | sh
          sleep 5
          ollama create volo -f ./Modelfile
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Node Requirements
        run: npm install
      - uses: cypress-io/github-action@v6
        with:
          config-file: ${{ github.workspace }}/cypress/cypress.config.ts
          record: true
          start: npx ts-node cypress/run.ts
          wait-on: 'http://localhost:8000'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: Screenshot
          path: ${{ github.workspace }}/cypress/screenshots/
